### ISSUE TITLE
Error en make deploy send_reservation_email

### ISSUE THREAD

**Issue by arielbrizi** [migdress/sls-aws-airline#1]
Me arroja este error:

CloudFormation - CREATE_FAILED - AWS::Lambda::EventSourceMapping - V1EventSourceMappingSQSSqsnotifications
.....
CloudFormation - CREATE_FAILED - AWS::Lambda::Version - V1LambdaVersionQtu4Ogne1cb6su4fmn6cCNH5jlAuxzZX2gMNjUj3L4
......
  An error occurred: V1EventSourceMappingSQSSqsnotifications - 1 validation error detected: Value 'arn:aws:sqs:us-east-1:account:sqs_notifications' at 'eventSourceArn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws[a-zA-Z0-9-]*):([a-zA-Z0-9\-])+:([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1})?:(\d{12})?:(.*) (Service: AWSLambda; Status Code: 400; Error Code: ValidationException; Request ID: 8a194c82-0bc5-4383-ac3a-9d36c8c5f61b).

Estara bien el file ".../sls-aws-airline/flights/reserve_seat/serverless.yml"  ?

Con los otros dos deploys no me paso

**Comment by migdress** [comment]
Hola! acabo de revisar y no tuve problema en el despliegue, aunque tus logs mencionan algo de la queue `sqs_notifications`, tienes la cola de sqs creada con ese nombre? o quizás modificaste algún nombre de las funciones lambda?

**Comment by arielbrizi** [comment]
como charlamos, era el tema de definir bien el target en los archivos de configuracion y makefile. gracias!!
